# Generated by Django 3.2.16 on 2023-01-02 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Book', max_length=100, unique=True)),
                ('shortDescription', models.CharField(default='Short Descpriton for the book', max_length=1000)),
                ('resume', models.CharField(default='descprtion', max_length=3000)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('category', models.CharField(choices=[('dv', 'diversifié'), ('dr', 'dramatique'), ('su', 'suspense'), ('na', 'naratif'), ('ac', 'action'), ('sc', 'science'), ('o', 'others')], default='o', max_length=15)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('is_available', models.BooleanField(default=True)),
                ('bookImage', models.ImageField(upload_to='images/')),
                ('published_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mybook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_book', to='Account.book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbBooks', models.IntegerField()),
                ('period_rental', models.IntegerField(default=10, max_length=4)),
                ('meetingPlace', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('P', 'pending'), ('S', 'success'), ('F', 'fail'), ('C', 'challenged')], default='P', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_client', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_seller', to=settings.AUTH_USER_MODEL)),
                ('target_book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='Account.book')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SA', 'SAGA'), ('CH', 'CHAPITRE'), ('TR', 'TRILOGIE'), ('SS', 'SAISON')], default='noType', max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='Account.book')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cb_book', to='Account.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cb_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=8)),
                ('lastName', models.CharField(default='', max_length=8)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('accountType', models.CharField(choices=[('lb', 'libraire'), ('cl', 'client')], default='cl', max_length=2)),
                ('adress', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=20)),
                ('zipCode', models.CharField(default='0000', max_length=5)),
                ('phone_number', models.CharField(default='0658248398', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
