# Generated by Django 3.2.16 on 2023-01-07 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenged_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_user', to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challege_operation', to='Account.operation')),
            ],
        ),
    ]
