# Generated by Django 3.2.16 on 2022-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fisrtName',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('lb', 'libraire'), ('cl', 'client')], max_length=7),
        ),
    ]
