# Generated by Django 3.2.16 on 2023-01-09 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_challengedoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='rental_start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('S', 'success'), ('F', 'fail'), ('C', 'challenged'), ('R', 'restored')], default='P', max_length=15),
        ),
    ]
