# Generated by Django 3.2.16 on 2022-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20221025_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('lb', 'libraire'), ('cl', 'client')], default='cl', max_length=7),
        ),
    ]
