# Generated by Django 3.2.16 on 2022-11-15 09:48

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='account',
            name='zipCode',
            field=models.CharField(default='0000', max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('lb', 'libraire'), ('cl', 'client')], default='cl', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
