# Generated by Django 3.2.16 on 2023-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20230109_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.CharField(default='Alilou Raid', max_length=20),
        ),
    ]
