# Generated by Django 3.2.16 on 2023-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20230114_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
