# Generated by Django 3.2.16 on 2023-01-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_readinggroup_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='adresse',
            field=models.CharField(default='1 rue etoile', max_length=30),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='city',
            field=models.CharField(default='Paris', max_length=10),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='codeZip',
            field=models.IntegerField(default='75001', max_length=5),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='eventDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='nbMembers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(upload_to='../images/'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='img',
            field=models.ImageField(upload_to='../images/'),
        ),
    ]
