# Generated by Django 3.2.16 on 2023-01-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20230115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='city',
            field=models.CharField(default='Paris', max_length=50),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='codeZip',
            field=models.IntegerField(default=75001, max_length=10),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(14, 18, 31, 144312)),
        ),
    ]
