# Generated by Django 3.2.16 on 2023-01-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20230116_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(14, 18, 44, 575137)),
        ),
    ]
