# Generated by Django 3.2.16 on 2023-01-17 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_readinggroup_eventmoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(10, 58, 59, 103351)),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
