# Generated by Django 3.2.16 on 2023-01-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20230117_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(11, 46, 46, 862087)),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
