# Generated by Django 3.2.16 on 2023-01-18 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_readinggroup_eventmoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(upload_to='./media'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(9, 46, 7, 101022)),
        ),
    ]
