# Generated by Django 3.2.16 on 2023-01-18 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_auto_20230118_0946'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readinggroup',
            name='unique_OwnerGroup_targetBook_combination',
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(10, 45, 50, 81457)),
        ),
        migrations.AddConstraint(
            model_name='readinggroup',
            constraint=models.UniqueConstraint(fields=('created_by', 'book', 'eventDate', 'eventMoment'), name='unique_ReadingGroup_contraint'),
        ),
    ]
