# Generated by Django 3.2.16 on 2023-01-18 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_auto_20230118_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(default='bookPictures/droit.jpeg', null=True, upload_to='bookPictures'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='eventMoment',
            field=models.TimeField(default=datetime.time(13, 25, 22, 521020)),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='img',
            field=models.ImageField(default='bookPictures/droit.jpeg', null=True, upload_to='bookPictures'),
        ),
    ]
